version: '3'

services:
  api:
    image: alpine
    container_name: api
    restart: unless-stopped
    command:
      - /bin/sh
      - -c
      - "nc -l -p 8000"
    ports:
      - 8000:8000
  proxy:
    image: envoyproxy/envoy:v1.16.0
    container_name: proxy
    restart: unless-stopped
    command: "/usr/local/bin/envoy -c /etc/envoy/envoy.yaml --service-cluster 'service-a' --service-node 'service-a'"
    ports:
      - 10000:10000
    volumes:
      - ./config/envoy.yaml:/etc/envoy/envoy.yaml
      - ./secret/token-secret.yaml:/etc/envoy/token-secret.yaml
      - ./secret/hmac.yaml:/etc/envoy/hmac.yaml
